### ISSUE TITLE
使源码安装完成后，使用python main.py后运行，疑似网络问题导致10054（本人无能力解决故申请issues）

### ISSUE THREAD

**Issue by AnonCN** [sMythicalBird/ZenlessZoneZero-Auto#109]
`2024-08-03 11:28:20.647 | ERROR    | utils.download:check_file_task:98 - 检查文件失败！
Traceback (most recent call last):

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               │    └ <function HTTPConnectionPool._make_request at 0x000000000341F490>
               └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x00000000247EEB30>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
          └ ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x00000000247EF400>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x000000000341F880>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x00000000247EEB30>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x0000000003413E20>
    └ <urllib3.connection.HTTPSConnection object at 0x00000000247EF400>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        └ <function _ssl_wrap_socket_and_match_hostname at 0x00000000033C57E0>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               └ <function ssl_wrap_socket at 0x0000000003347880>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               │                     │     │        │           └ 'zzz.caiyun.fun'
               │                     │     │        └ False
               │                     │     └ <ssl.SSLContext object at 0x000000000396F7C0>
               │                     └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
               └ <function _ssl_wrap_socket_impl at 0x0000000003347A30>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'zzz.caiyun.fun'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
           │           └ <function SSLContext.wrap_socket at 0x000000000329A0E0>
           └ <ssl.SSLContext object at 0x000000000396F7C0>

  File "C:\ProgramData\miniconda3\envs\py310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod(<function SSLSocket._create at 0x000000000329BC70>)>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x000000000396F7C0>

  File "C:\ProgramData\miniconda3\envs\py310\lib\ssl.py", line 1104, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x000000000330CF70>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>

  File "C:\ProgramData\miniconda3\envs\py310\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>

ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x000000000341F640>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x00000000247EEB30>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x00000000033448B0>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          │            │       │      └ <traceback object at 0x0000000023D7DF80>
          │            │       └ ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
          │            └ ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
          └ <function reraise at 0x000000000330EF80>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
          │                    └ None
          └ None

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               │    └ <function HTTPConnectionPool._make_request at 0x000000000341F490>
               └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x00000000247EEB30>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
          └ ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x00000000247EF400>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x000000000341F880>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x00000000247EEB30>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x0000000003413E20>
    └ <urllib3.connection.HTTPSConnection object at 0x00000000247EF400>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        └ <function _ssl_wrap_socket_and_match_hostname at 0x00000000033C57E0>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               └ <function ssl_wrap_socket at 0x0000000003347880>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               │                     │     │        │           └ 'zzz.caiyun.fun'
               │                     │     │        └ False
               │                     │     └ <ssl.SSLContext object at 0x000000000396F7C0>
               │                     └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
               └ <function _ssl_wrap_socket_impl at 0x0000000003347A30>

  File "C:\ProgramData\miniconda3\envs\py310\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'zzz.caiyun.fun'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
           │           └ <function SSLContext.wrap_socket at 0x000000000329A0E0>
           └ <ssl.SSLContext object at 0x000000000396F7C0>

  File "C:\ProgramData\miniconda3\envs\py310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod(<function SSLSocket._create at 0x000000000329BC70>)>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x000000000396F7C0>

  File "C:\ProgramData\miniconda3\envs\py310\lib\ssl.py", line 1104, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x000000000330CF70>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>

  File "C:\ProgramData\miniconda3\envs\py310\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))`

[logger.log](https://github.com/user-attachments/files/16477941/logger.log)
请作者忽视附件代码中的前两行

**Comment by lazydog28** [comment]
这个问题暂时没有解决的办法，可以尝试更换网络或者将检查文件更新的代码注释掉。

**Comment by lazydog28** [comment]
utils.download.py文件内的

 ​check_file_task​()
