### ISSUE TITLE
pip找不到名为mesonpy的模块。

### ISSUE THREAD

**Issue by XIYBHK** [sMythicalBird/ZenlessZoneZero-Auto#120]
报错提示
ERROR: Exception:
Traceback (most recent call last):
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 186, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
    super().__init__(
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\utils\misc.py", line 706, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "D:\jiaoben\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

2024/08/05 03:03:11 exit status 2

**Comment by lazydog28** [comment]
https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/113#issuecomment-2267362183

**Comment by XIYBHK** [comment]
OK 解决 第一次尝试时我只修改了requirements-dml文件 没有解决 后续修改了requirements和requirements-cpu 后可以使用自动安装 感谢
