### ISSUE TITLE
[BUG] 读取onnxruntime_providers_cuda.dll时出现报错

### ISSUE THREAD

**Issue by LINKlang** [sMythicalBird/ZenlessZoneZero-Auto#13]
GPU模式，本地安装CUDA和cuDNN

CUDA版本：12.3
cuDNN版本：8.9.7 for CUDA 12.x

![image](https://github.com/user-attachments/assets/37a76338-a31a-4855-aefa-352d1d6d624c)

log
```
024-07-15 17:23:37.401 | INFO     | utils.detect.current:<module>:24 - 使用 CUDAExecutionProvider 运行当前位置识别模型
2024-07-15 17:23:37.4641294 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Python\ZenlessZoneZero-Auto\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-07-15 17:23:37.5256167 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Python\ZenlessZoneZero-Auto\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "D:\Python\ZenlessZoneZero-Auto\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\Python\ZenlessZoneZero-Auto\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers) 
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\Python\ZenlessZoneZero-Auto\main.py", line 4, in <module>
    from handle import *
  File "d:\Python\ZenlessZoneZero-Auto\handle\__init__.py", line 16, in <module>
    from .others import *
  File "d:\Python\ZenlessZoneZero-Auto\handle\others.py", line 15, in <module>
    from utils.detect.current import find_current
  File "d:\Python\ZenlessZoneZero-Auto\utils\detect\current.py", line 25, in <module>
    model = rt.InferenceSession(model_path, providers=provider)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
```

**Comment by LINKlang** [comment]
疑似requirements覆盖了我的paddle，重新安装paddle后正常运行
