### ISSUE TITLE
Failed to create CUDAExecutionProvider

### ISSUE THREAD

**Issue by ChenSV-github** [sMythicalBird/ZenlessZoneZero-Auto#137]
2024-08-08 21:43:38.872 | INFO     | utils.detect.current:<module>:18 - 使用 CUDAExecutionProvider 运行当前位置识别模型
2024-08-08 21:43:38.9311958 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\B760-A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-08-08 21:43:38.9401202 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:861 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
2024-08-08 21:43:39.2846114 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\B760-A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-08-08 21:43:39.2877690 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:861 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
2024-08-08 21:43:39.3535563 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\B760-A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-08-08 21:43:39.3634240 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:861 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
2024-08-08 21:43:39.639 | DEBUG    | utils:<module>:38 - 初始化utils模块完成
2024-08-08 21:43:39.639 | INFO     | utils:<module>:41 - 当前版本：072800
2024-08-08 21:43:39.677 | DEBUG    | utils.ocr.ocr:__init__:47 - 初始化OCR
2024-08-08 21:43:53.550 | DEBUG    | utils.ocr.ocr:__init__:81 - 使用GPU进行OCR识别
2024-08-08 21:43:59.049 | DEBUG    | utils.ocr.ocr:__init__:92 - 初始化OCR完成
2024-08-08 21:43:59.065 | DEBUG    | utils.task:decorator:275 - 添加页面：通用点击事件
2024-08-08 21:43:59.066 | DEBUG    | utils.task:decorator:275 - 添加页面：确定操作
2024-08-08 21:43:59.066 | DEBUG    | utils.task:decorator:275 - 添加页面：确认操作
2024-08-08 21:43:59.066 | DEBUG    | utils.task:decorator:275 - 添加页面：丢弃操作
2024-08-08 21:43:59.066 | DEBUG    | utils.task:decorator:275 - 添加页面：清除侵蚀效果
2024-08-08 21:43:59.067 | DEBUG    | utils.task:decorator:275 - 添加页面：目标位置
2024-08-08 21:43:59.067 | DEBUG    | utils.task:decorator:275 - 添加页面：资源回收小组
2024-08-08 21:43:59.067 | DEBUG    | utils.task:decorator:275 - 添加页面：调查协会支援站
2024-08-08 21:43:59.067 | DEBUG    | utils.task:decorator:275 - 添加页面：调查协会支援站_狡兔屋
2024-08-08 21:43:59.067 | DEBUG    | utils.task:decorator:275 - 添加页面：馅饼天降
2024-08-08 21:43:59.068 | DEBUG    | utils.task:decorator:275 - 添加页面：呼叫增援_接应
2024-08-08 21:43:59.068 | DEBUG    | utils.task:decorator:275 - 添加页面：呼叫增援_入队
2024-08-08 21:43:59.068 | DEBUG    | utils.task:decorator:275 - 添加页面：呼叫增援_对话
2024-08-08 21:43:59.068 | DEBUG    | utils.task:decorator:275 - 添加页面：催化
2024-08-08 21:43:59.068 | DEBUG    | utils.task:decorator:275 - 添加页面：投机客
2024-08-08 21:43:59.069 | DEBUG    | utils.task:decorator:275 - 添加页面：投机客_帮助_回复生命
2024-08-08 21:43:59.069 | DEBUG    | utils.task:decorator:275 - 添加页面：投机客_帮助_清除压力
2024-08-08 21:43:59.069 | DEBUG    | utils.task:decorator:275 - 添加页面：投机客_离开
2024-08-08 21:43:59.069 | DEBUG    | utils.task:decorator:275 - 添加页面：坍塌的房屋
2024-08-08 21:43:59.069 | DEBUG    | utils.task:decorator:275 - 添加页面：精锐邦布助手
2024-08-08 21:43:59.070 | DEBUG    | utils.task:decorator:275 - 添加页面：退出特殊区域
2024-08-08 21:43:59.070 | DEBUG    | utils.task:decorator:275 - 添加页面：降低压力值
2024-08-08 21:43:59.070 | DEBUG    | utils.task:decorator:275 - 添加页面：不感兴趣
2024-08-08 21:43:59.070 | DEBUG    | utils.task:decorator:275 - 添加页面：假面研究者
2024-08-08 21:43:59.070 | DEBUG    | utils.task:decorator:275 - 添加页面：假面研究者_物资
2024-08-08 21:43:59.070 | DEBUG    | utils.task:decorator:275 - 添加页面：假面研究者_降压
2024-08-08 21:43:59.071 | DEBUG    | utils.task:decorator:275 - 添加页面：假面研究者_催化
2024-08-08 21:43:59.071 | DEBUG    | utils.task:decorator:275 - 添加页面：邦布商人_鸣徽交易
2024-08-08 21:43:59.071 | DEBUG    | utils.task:decorator:275 - 添加页面：邦布商人_鸣徽催化
2024-08-08 21:43:59.071 | DEBUG    | utils.task:decorator:275 - 添加页面：进入特殊区域
2024-08-08 21:43:59.072 | DEBUG    | utils.task:decorator:275 - 添加页面：旧都往事系列收集品
2024-08-08 21:43:59.072 | DEBUG    | utils.task:decorator:275 - 添加页面：怀斯塔学会的援助
2024-08-08 21:43:59.072 | DEBUG    | utils.task:decorator:275 - 添加页面：老练的调查员
2024-08-08 21:43:59.072 | DEBUG    | utils.task:decorator:275 - 添加页面：治安局预备队
2024-08-08 21:43:59.072 | DEBUG    | utils.task:decorator:275 - 添加页面：邦布的秘宝
2024-08-08 21:43:59.073 | DEBUG    | utils.task:decorator:275 - 添加页面：异化检疫门
2024-08-08 21:43:59.073 | DEBUG    | utils.task:decorator:275 - 添加页面：抵押欠款
2024-08-08 21:43:59.074 | DEBUG    | utils.task:decorator:275 - 添加页面：助战邦布已满
2024-08-08 21:43:59.074 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_存款
2024-08-08 21:43:59.074 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_存血
2024-08-08 21:43:59.074 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_离开
2024-08-08 21:43:59.075 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_离开
2024-08-08 21:43:59.075 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_不要了
2024-08-08 21:43:59.075 | DEBUG    | utils.task:decorator:275 - 添加页面：零号业绩领取
2024-08-08 21:43:59.075 | DEBUG    | utils.task:decorator:275 - 添加页面：付费通道
2024-08-08 21:43:59.075 | DEBUG    | utils.task:decorator:275 - 添加页面：全自动医疗仓
2024-08-08 21:43:59.076 | DEBUG    | utils.task:decorator:275 - 添加页面：娱乐区幸运拉杆
2024-08-08 21:43:59.076 | DEBUG    | utils.task:decorator:275 - 添加页面：古怪装置
2024-08-08 21:43:59.082 | DEBUG    | handle.others:<module>:20 - 地图名称: 旧都列车, 地图等级: 外围
2024-08-08 21:43:59.082 | DEBUG    | utils.task:decorator:275 - 添加页面：地图层数
2024-08-08 21:43:59.082 | DEBUG    | utils.task:decorator:275 - 添加页面：炸弹
2024-08-08 21:43:59.083 | DEBUG    | utils.task:decorator:275 - 添加页面：选择角色
2024-08-08 21:43:59.083 | DEBUG    | utils.task:decorator:275 - 添加页面：选择副本
2024-08-08 21:43:59.084 | DEBUG    | utils.task:decorator:275 - 添加页面：选择副本等级
2024-08-08 21:43:59.084 | DEBUG    | utils.task:decorator:275 - 添加页面：退出
2024-08-08 21:43:59.084 | DEBUG    | utils.task:decorator:275 - 添加页面：结算界面
2024-08-08 21:43:59.090 | DEBUG    | utils.task:decorator:275 - 添加页面：红叉离开事件
2024-08-08 21:43:59.090 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_红色风险
2024-08-08 21:43:59.091 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_紫色风险
2024-08-08 21:43:59.091 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_白色未知
2024-08-08 21:43:59.092 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_蓝色打开
2024-08-08 21:43:59.092 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_金色收益
2024-08-08 21:43:59.094 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_蓝色收益
2024-08-08 21:43:59.094 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_绿色收益
2024-08-08 21:43:59.094 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_橙色插件
2024-08-08 21:43:59.095 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_白色退出
2024-08-08 21:43:59.095 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_绿色治疗
2024-08-08 21:43:59.104 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_艾莲1
2024-08-08 21:43:59.105 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_艾莲2
2024-08-08 21:43:59.105 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_猫又1
2024-08-08 21:43:59.105 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_猫又2
2024-08-08 21:43:59.105 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_格莉丝1
2024-08-08 21:43:59.111 | DEBUG    | utils.task:decorator:275 - 添加页面：选择_鸣徽
2024-08-08 21:43:59.137 | DEBUG    | utils.task:decorator:275 - 添加页面：战斗中
2024-08-08 21:43:59.138 | DEBUG    | utils.task:decorator:275 - 添加页面：打不过跑路
2024-08-08 21:43:59.138 | DEBUG    | utils.task:decorator:275 - 添加页面：打不过怪
Traceback (most recent call last):
  File "D:\ZenlessZoneZero-Auto-master\main.py", line 56, in <module>
    task.run()
  File "D:\ZenlessZoneZero-Auto-master\utils\task.py", line 360, in run
    self()  # 执行任务
  File "D:\ZenlessZoneZero-Auto-master\utils\task.py", line 321, in __call__
    ocr_results = self.ocr(img)  # OCR识别
  File "D:\ZenlessZoneZero-Auto-master\utils\ocr\ocr.py", line 162, in __call__
    return self.ocr(img)
  File "D:\ZenlessZoneZero-Auto-master\utils\ocr\ocr.py", line 109, in ocr
    results = self.paddleOCR.ocr(img, cls=False)[0]
  File "C:\Users\B760-A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paddleocr\paddleocr.py", line 668, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "C:\Users\B760-A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paddleocr\tools\infer\predict_system.py", line 76, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\Users\B760-A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paddleocr\tools\infer\predict_det.py", line 244, in __call__
    self.input_tensor.copy_from_cpu(img)
  File "C:\Users\B760-A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paddle\inference\wrapper.py", line 52, in tensor_copy_from_cpu
    self._copy_from_cpu_bind(data)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:312)

**Comment by lazydog28** [comment]
自己安装的conda环境还是用的一键启动？

**Comment by ChenSV-github** [comment]
自己安装的

**Comment by lazydog28** [comment]
cuda环境没装好
