### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by Scriopu** [sMythicalBird/ZenlessZoneZero-Auto#163]
変换鎰忛敭閫€鍑?..Traceback (most recent call last):
  File "G:\game\ZenlessZoneZero-Auto\main.py", line 31, in <module>
    from utils.task import task
  File "G:\game\ZenlessZoneZero-Auto\utils\__init__.py", line 8, in <module>
    from .download import check_file
  File "G:\game\ZenlessZoneZero-Auto\utils\download.py", line 14, in <module>
    from .init import logger, RootPath
  File "G:\game\ZenlessZoneZero-Auto\utils\init.py", line 106, in <module>
    wait_exit()
  File "G:\game\ZenlessZoneZero-Auto\utils\init.py", line 48, in wait_exit
    input("按任意键退出...")
    
    您好，截图功能不太会用。遇到了这串代码无法启动脚本，请问是什么原因？

**Comment by sMythicalBird** [comment]
去release下载一键包吧

**Comment by lazydog28** [comment]
根据报错信息，有以下的可能
* 没开游戏就直接启动脚本
* 获取屏幕缩放比例失败
* 游戏窗口分辨率不是1280x720
