### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by codeNewbie-bit** [sMythicalBird/ZenlessZoneZero-Auto#17]
2024-07-16 02:28:08.426 | DEBUG    | utils.task:__call__:334 - 当前页面：地图层数_1
Traceback (most recent call last):
  File "E:\code\ZenlessZoneZero-Auto-master\main.py", line 27, in <module>
    task.run()
  File "E:\code\ZenlessZoneZero-Auto-master\utils\task.py", line 367, in run
    self()  # 执行任务
    ^^^^^^
  File "E:\code\ZenlessZoneZero-Auto-master\utils\task.py", line 342, in __call__
    page.action(**params)  # 执行页面操作函数
    ^^^^^^^^^^^^^^^^^^^^^
  File "E:\code\ZenlessZoneZero-Auto-master\handle\others.py", line 49, in grid_map_1
    (mc, dirct) = info.mapWay[info.step]
                  ~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range

![error](https://github.com/user-attachments/assets/b96e7302-4054-42cb-a2d0-e804afcc78a5)

**Comment by lazydog28** [comment]
没有成功寻路到终点的路线

**Comment by lazydog28** [comment]
下个版本会进行修复

**Comment by sMythicalBird** [comment]
看一下屏幕缩放比例，这个会影响自动寻路，下个版本加了缩放的处理，当前版本还不支持缩放

**Comment by codeNewbie-bit** [comment]
> 看一下屏幕缩放比例，这个会影响自动寻路，下个版本加了缩放的处理，当前版本还不支持缩放

设置了1280X720分辨率，窗口模式

**Comment by sMythicalBird** [comment]
> > 看一下屏幕缩放比例，这个会影响自动寻路，下个版本加了缩放的处理，当前版本还不支持缩放
> 
> 设置了1280X720分辨率，窗口模式

这个缩放指的是显示设置里的百分比缩放，这个会影响截图做图片分类，当前版本这部分是写死的

**Comment by codeNewbie-bit** [comment]
> > > 看一下屏幕缩放比例，这个会影响自动寻路，下个版本加了缩放的处理，当前版本还不支持缩放
> > 
> > 
> > 设置了1280X720分辨率，窗口模式
> 
> 这个缩放指的是显示设置里的百分比缩放，这个会影响截图做图片分类，当前版本这部分是写死的

是电脑系统里的缩放与布局吗 ？ 是默认的100% 没改过
