### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by smallmj** [sMythicalBird/ZenlessZoneZero-Auto#188]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### 系统版本

Windows 11

### bug情况描述

(py310) c:\zzz\ZenlessZoneZero-Auto>python main.py

 --------------------------------------------------------------
     注意：此脚本为免费的开源软件，如果你是通过购买获得的，那么你受骗了！
--------------------------------------------------------------

使用说明：
   F10  恢复运行
   F11  暂停运行
   F12  结束运行

2024-08-16 18:25:01.604 | DEBUG    | utils.init:<module>:32 - 初始化utils模块中
2024-08-16 18:25:01.618 | DEBUG    | utils.init:<module>:77 - 将游戏窗口移动到屏幕左上角
2024-08-16 18:25:01.622 | INFO     | utils.init:<module>:100 - 游戏窗口宽度为1024，高度为576,缩放因子为1.25,实际宽度为1280,实际高度为720
2024-08-16 18:25:01.622 | INFO     | utils.init:<module>:103 - 菜单栏高度为28,左上角偏移量为(9.0,38.5)
2024-08-16 18:25:01.623 | DEBUG    | utils.download:check_file_task:94 - 开始检查文件！
2024-08-16 18:25:01.859 | DEBUG    | utils.download:check_file:82 - 文件检查完成！
Executing utils module
2024-08-16 18:25:02.038 | INFO     | utils.config:load_config:24 - 加载配置文件 c:\zzz\ZenlessZoneZero-Auto\config.yaml
2024-08-16 18:25:02.040 | INFO     | utils.config:load_config:35 - 配置文件加载成功
2024-08-16 18:25:02.041 | INFO     | utils.config:load_tactics:46 - 未检测到 c:\zzz\ZenlessZoneZero-Auto\fight\tactics 目录，请在 c:\zzz\ZenlessZoneZero-Auto\fight\tactics 目录下添加战斗策略文件
2024-08-16 18:25:02.041 | INFO     | utils.config:load_tactics:50 - 将使用 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults 默认目录加载战斗策略文件
2024-08-16 18:25:02.042 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\妮可.yaml
2024-08-16 18:25:02.043 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\安比.yaml
2024-08-16 18:25:02.044 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\朱鸢.yaml
2024-08-16 18:25:02.051 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\格莉丝.yaml
2024-08-16 18:25:02.056 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\红光.yaml
2024-08-16 18:25:02.057 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\艾莲.yaml
2024-08-16 18:25:02.060 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\艾莲技能.yaml
2024-08-16 18:25:02.062 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\苍角.yaml
2024-08-16 18:25:02.064 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\莱卡恩.yaml
2024-08-16 18:25:02.066 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\连携.yaml
2024-08-16 18:25:02.068 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\青衣.yaml
2024-08-16 18:25:02.070 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\黄光.yaml
2024-08-16 18:25:02.072 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 c:\zzz\ZenlessZoneZero-Auto\fight\tactics_defaults\默认.yaml
2024-08-16 18:25:02.077 | INFO     | utils.config:load_characters:70 - 加载人物头像 c:\zzz\ZenlessZoneZero-Auto\fight\characters
2024-08-16 18:25:02.190 | INFO     | utils.detect.current:<module>:18 - 使用 CUDAExecutionProvider 运行当前位置识别模型
*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-568427808 ; hostname=DESKTOP-GTTIL9R ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);

 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\ProgramData\anaconda3\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-568427808 ; hostname=DESKTOP-GTTIL9R ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\zzz\ZenlessZoneZero-Auto\main.py", line 31, in <module>
    from utils.task import task
  File "c:\zzz\ZenlessZoneZero-Auto\utils\__init__.py", line 19, in <module>
    from .map import get_map_info, auto_find_way
  File "c:\zzz\ZenlessZoneZero-Auto\utils\map\__init__.py", line 8, in <module>
    from .components import get_map_info
  File "c:\zzz\ZenlessZoneZero-Auto\utils\map\components.py", line 15, in <module>
    from ..detect import Model, find_current
  File "c:\zzz\ZenlessZoneZero-Auto\utils\detect\__init__.py", line 9, in <module>
    from .current import find_current
  File "c:\zzz\ZenlessZoneZero-Auto\utils\detect\current.py", line 19, in <module>
    model = InferenceSession(str(model_path), providers=Provider)
  File "C:\ProgramData\anaconda3\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\ProgramData\anaconda3\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\ProgramData\anaconda3\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-568427808 ; hostname=DESKTOP-GTTIL9R ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);

运行后报错。

**Comment by smallmj** [comment]
核显选了gpu模式报错了，改成cpu模式解决了
