### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DAI-HY** [sMythicalBird/ZenlessZoneZero-Auto#193]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### 系统版本

Windows 11

### bug情况描述

CUDA 版本是12.6 这会是跟toolkit版本冲突的问题吗？

### 上传截图

Windows PowerShell
版权所有（C） Microsoft Corporation。保留所有权利。

安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS C:\WINDOWS\system32> cd D:\FUZHU\ZenlessZoneZero-Auto-master
PS D:\FUZHU\ZenlessZoneZero-Auto-master> python main.py

 --------------------------------------------------------------
     注意：此脚本为免费的开源软件，如果你是通过购买获得的，那么你受骗了！
--------------------------------------------------------------

使用说明：
   F10  恢复运行
   F11  暂停运行
   F12  结束运行

C:\Users\DAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
2024-08-17 19:14:25.748 | DEBUG    | utils.init:<module>:32 - 初始化utils模块中
2024-08-17 19:14:25.773 | DEBUG    | utils.init:<module>:77 - 将游戏窗口移动到屏幕左上角
2024-08-17 19:14:25.773 | INFO     | utils.init:<module>:100 - 游戏窗口宽度为1280，高度为720,缩放因子为1.0,实际宽度为1280,实际高度为720
2024-08-17 19:14:25.774 | INFO     | utils.init:<module>:103 - 菜单栏高度为22,左上角偏移量为(8.0,31.0)
2024-08-17 19:14:25.774 | DEBUG    | utils.download:check_file_task:94 - 开始检查文件！
2024-08-17 19:14:27.303 | DEBUG    | utils.download:check_file:82 - 文件检查完成！
Executing utils module
2024-08-17 19:14:27.459 | INFO     | utils.config:load_config:24 - 加载配置文件 D:\FUZHU\ZenlessZoneZero-Auto-master\config.yaml
2024-08-17 19:14:27.460 | INFO     | utils.config:load_config:35 - 配置文件加载成功
2024-08-17 19:14:27.461 | INFO     | utils.config:load_tactics:46 - 未检测到 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics 目录，请在 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics 目录下添加战斗策略文件
2024-08-17 19:14:27.461 | INFO     | utils.config:load_tactics:50 - 将使用 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults 默认目录加载战斗策略文件
2024-08-17 19:14:27.462 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\11号.yaml
2024-08-17 19:14:27.464 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\妮可.yaml
2024-08-17 19:14:27.465 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\安比.yaml
2024-08-17 19:14:27.466 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\朱鸢.yaml
2024-08-17 19:14:27.468 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\格莉丝.yaml
2024-08-17 19:14:27.469 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\红光.yaml
2024-08-17 19:14:27.470 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\艾莲.yaml
2024-08-17 19:14:27.472 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\艾莲技能.yaml
2024-08-17 19:14:27.473 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\苍角.yaml
2024-08-17 19:14:27.475 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\莱卡恩.yaml
2024-08-17 19:14:27.476 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\连携.yaml
2024-08-17 19:14:27.477 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\青衣.yaml
2024-08-17 19:14:27.479 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\黄光.yaml
2024-08-17 19:14:27.480 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\默认.yaml
2024-08-17 19:14:27.482 | INFO     | utils.config:load_characters:70 - 加载人物头像 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\characters
2024-08-17 19:14:27.629 | INFO     | utils.detect.current:<module>:18 - 使用 CUDAExecutionProvider 运行当前位置识别模型
2024-08-17 19:14:27.7302876 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\DAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-08-17 19:14:27.7630938 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\DAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "C:\Users\DAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\DAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FUZHU\ZenlessZoneZero-Auto-master\main.py", line 31, in <module>
    from utils.task import task
  File "D:\FUZHU\ZenlessZoneZero-Auto-master\utils\__init__.py", line 19, in <module>
    from .map import get_map_info, auto_find_way
  File "D:\FUZHU\ZenlessZoneZero-Auto-master\utils\map\__init__.py", line 8, in <module>
    from .components import get_map_info
  File "D:\FUZHU\ZenlessZoneZero-Auto-master\utils\map\components.py", line 15, in <module>
    from ..detect import Model, find_current
  File "D:\FUZHU\ZenlessZoneZero-Auto-master\utils\detect\__init__.py", line 9, in <module>
    from .current import find_current
  File "D:\FUZHU\ZenlessZoneZero-Auto-master\utils\detect\current.py", line 19, in <module>
    model = InferenceSession(str(model_path), providers=Provider)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\Users\DAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\DAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.

**Comment by lazydog28** [comment]
[onnxruntime版本要求](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html)

请自行检查CUDA版本和CUDNN版本
