### ISSUE TITLE
[Bug]: 总是出现情急截图失败

### ISSUE THREAD

**Issue by DAI-HY** [sMythicalBird/ZenlessZoneZero-Auto#199]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### bug情况描述

清理截图失败，然后zzz直接关闭 就剩个cmd窗口在桌面上

### 上传截图

使用说明：
   F10  恢复运行
   F11  暂停运行
   F12  结束运行

2024-08-18 15:30:47.415 | DEBUG    | utils.init:<module>:32 - 初始化utils模块中
2024-08-18 15:30:47.441 | DEBUG    | utils.init:<module>:77 - 将游戏窗口移动到屏幕左上角
2024-08-18 15:30:47.442 | INFO     | utils.init:<module>:100 - 游戏窗口宽度为1280，高度为720,缩放因子为1.0,实际宽度为1280,实际高度为720
2024-08-18 15:30:47.443 | INFO     | utils.init:<module>:103 - 菜单栏高度为22,左上角偏移量为(8.0,31.0)
2024-08-18 15:30:47.443 | DEBUG    | utils.download:check_file_task:94 - 开始检查文件！
2024-08-18 15:30:48.629 | DEBUG    | utils.download:check_file:82 - 文件检查完成！
Executing utils module
2024-08-18 15:30:48.825 | INFO     | utils.config:load_config:24 - 加载配置文件 D:\FUZHU\ZenlessZoneZero-Auto-master\config.yaml
2024-08-18 15:30:48.827 | INFO     | utils.config:load_config:35 - 配置文件加载成功
2024-08-18 15:30:48.827 | INFO     | utils.config:load_tactics:46 - 未检测到 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics 目录，请在 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics 目录下添加战斗策略文件
2024-08-18 15:30:48.827 | INFO     | utils.config:load_tactics:50 - 将使用 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults 默认目录加载战斗策略文件
2024-08-18 15:30:48.828 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\11号.yaml
2024-08-18 15:30:48.830 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\妮可.yaml
2024-08-18 15:30:48.831 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\安比.yaml
2024-08-18 15:30:48.832 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\朱鸢.yaml
2024-08-18 15:30:48.834 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\格莉丝.yaml
2024-08-18 15:30:48.835 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\红光.yaml
2024-08-18 15:30:48.836 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\艾莲.yaml
2024-08-18 15:30:48.838 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\艾莲技能.yaml
2024-08-18 15:30:48.840 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\苍角.yaml
2024-08-18 15:30:48.841 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\莱卡恩.yaml
2024-08-18 15:30:48.842 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\连携.yaml
2024-08-18 15:30:48.843 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\青衣.yaml
2024-08-18 15:30:48.845 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\黄光.yaml
2024-08-18 15:30:48.847 | INFO     | utils.config:load_tactics:53 - 加载战斗策略文件 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\tactics_defaults\默认.yaml
2024-08-18 15:30:48.854 | INFO     | utils.config:load_characters:70 - 加载人物头像 D:\FUZHU\ZenlessZoneZero-Auto-master\fight\characters
2024-08-18 15:30:49.001 | INFO     | utils.detect.current:<module>:18 - 使用 CPUExecutionProvider 运行当前位置识别模型
2024-08-18 15:30:49.185 | DEBUG    | utils:<module>:38 - 初始化utils模块完成
2024-08-18 15:30:49.186 | INFO     | utils:<module>:41 - 当前版本：240806
2024-08-18 15:30:49.197 | DEBUG    | utils.ocr.ocr:__init__:47 - 初始化OCR
2024-08-18 15:30:51.394 | DEBUG    | utils.ocr.ocr:__init__:81 - 使用CPU进行OCR识别
2024-08-18 15:30:51.977 | DEBUG    | utils.ocr.ocr:__init__:92 - 初始化OCR完成
2024-08-18 15:30:51.981 | DEBUG    | utils.task:decorator:275 - 添加页面：通用点击事件
2024-08-18 15:30:51.984 | DEBUG    | utils.task:decorator:275 - 添加页面：确定操作
2024-08-18 15:30:51.984 | DEBUG    | utils.task:decorator:275 - 添加页面：确认操作
2024-08-18 15:30:51.984 | DEBUG    | utils.task:decorator:275 - 添加页面：丢弃操作
2024-08-18 15:30:51.984 | DEBUG    | utils.task:decorator:275 - 添加页面：清除侵蚀效果
2024-08-18 15:30:51.985 | DEBUG    | utils.task:decorator:275 - 添加页面：目标位置
2024-08-18 15:30:51.985 | DEBUG    | utils.task:decorator:275 - 添加页面：调查协会支援站
2024-08-18 15:30:51.985 | DEBUG    | utils.task:decorator:275 - 添加页面：调查协会支援站_狡兔屋
2024-08-18 15:30:51.985 | DEBUG    | utils.task:decorator:275 - 添加页面：馅饼天降
2024-08-18 15:30:51.986 | DEBUG    | utils.task:decorator:275 - 添加页面：呼叫增援_接应
2024-08-18 15:30:51.986 | DEBUG    | utils.task:decorator:275 - 添加页面：呼叫增援_入队
2024-08-18 15:30:51.986 | DEBUG    | utils.task:decorator:275 - 添加页面：呼叫增援_对话
2024-08-18 15:30:51.986 | DEBUG    | utils.task:decorator:275 - 添加页面：催化
2024-08-18 15:30:51.987 | DEBUG    | utils.task:decorator:275 - 添加页面：投机客
2024-08-18 15:30:51.987 | DEBUG    | utils.task:decorator:275 - 添加页面：投机客_帮助_回复生命
2024-08-18 15:30:51.987 | DEBUG    | utils.task:decorator:275 - 添加页面：投机客_帮助_清除压力
2024-08-18 15:30:51.987 | DEBUG    | utils.task:decorator:275 - 添加页面：投机客_离开
2024-08-18 15:30:51.988 | DEBUG    | utils.task:decorator:275 - 添加页面：坍塌的房屋
2024-08-18 15:30:51.988 | DEBUG    | utils.task:decorator:275 - 添加页面：精锐邦布助手
2024-08-18 15:30:51.988 | DEBUG    | utils.task:decorator:275 - 添加页面：退出特殊区域
2024-08-18 15:30:51.988 | DEBUG    | utils.task:decorator:275 - 添加页面：降低压力值
2024-08-18 15:30:51.989 | DEBUG    | utils.task:decorator:275 - 添加页面：不感兴趣
2024-08-18 15:30:51.989 | DEBUG    | utils.task:decorator:275 - 添加页面：假面研究者
2024-08-18 15:30:51.989 | DEBUG    | utils.task:decorator:275 - 添加页面：假面研究者_物资
2024-08-18 15:30:51.989 | DEBUG    | utils.task:decorator:275 - 添加页面：假面研究者_降压
2024-08-18 15:30:51.990 | DEBUG    | utils.task:decorator:275 - 添加页面：假面研究者_催化
2024-08-18 15:30:51.990 | DEBUG    | utils.task:decorator:275 - 添加页面：邦布商人_鸣徽交易
2024-08-18 15:30:51.990 | DEBUG    | utils.task:decorator:275 - 添加页面：邦布商人_鸣徽催化
2024-08-18 15:30:51.991 | DEBUG    | utils.task:decorator:275 - 添加页面：进入特殊区域
2024-08-18 15:30:51.991 | DEBUG    | utils.task:decorator:275 - 添加页面：旧都往事系列收集品
2024-08-18 15:30:51.991 | DEBUG    | utils.task:decorator:275 - 添加页面：老练的调查员
2024-08-18 15:30:51.992 | DEBUG    | utils.task:decorator:275 - 添加页面：治安局预备队
2024-08-18 15:30:51.992 | DEBUG    | utils.task:decorator:275 - 添加页面：邦布的秘宝
2024-08-18 15:30:51.992 | DEBUG    | utils.task:decorator:275 - 添加页面：异化检疫门
2024-08-18 15:30:51.993 | DEBUG    | utils.task:decorator:275 - 添加页面：抵押欠款
2024-08-18 15:30:51.993 | DEBUG    | utils.task:decorator:275 - 添加页面：助战邦布已满
2024-08-18 15:30:51.993 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_存款
2024-08-18 15:30:51.993 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_存血
2024-08-18 15:30:51.994 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_离开
2024-08-18 15:30:51.994 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_离开
2024-08-18 15:30:51.994 | DEBUG    | utils.task:decorator:275 - 添加页面：零号银行_不要了
2024-08-18 15:30:51.994 | DEBUG    | utils.task:decorator:275 - 添加页面：零号业绩领取
2024-08-18 15:30:51.995 | DEBUG    | utils.task:decorator:275 - 添加页面：付费通道
2024-08-18 15:30:52.003 | DEBUG    | utils.task:decorator:275 - 添加页面：全自动医疗仓
2024-08-18 15:30:52.003 | DEBUG    | utils.task:decorator:275 - 添加页面：娱乐区幸运拉杆
2024-08-18 15:30:52.004 | DEBUG    | utils.task:decorator:275 - 添加页面：事件有偿休息站
2024-08-18 15:30:52.004 | DEBUG    | utils.task:decorator:275 - 添加页面：事件安全车箱特殊处理
2024-08-18 15:30:52.005 | DEBUG    | handle.others:<module>:20 - 地图名称: 旧都列车, 地图等级: 腹地
2024-08-18 15:30:52.005 | DEBUG    | utils.task:decorator:275 - 添加页面：地图层数
2024-08-18 15:30:52.006 | DEBUG    | utils.task:decorator:275 - 添加页面：炸弹
2024-08-18 15:30:52.006 | DEBUG    | utils.task:decorator:275 - 添加页面：选择角色
2024-08-18 15:30:52.006 | DEBUG    | utils.task:decorator:275 - 添加页面：选择副本
2024-08-18 15:30:52.006 | DEBUG    | utils.task:decorator:275 - 添加页面：选择副本等级
2024-08-18 15:30:52.007 | DEBUG    | utils.task:decorator:275 - 添加页面：退出
2024-08-18 15:30:52.007 | DEBUG    | utils.task:decorator:275 - 添加页面：结算界面
2024-08-18 15:30:52.007 | DEBUG    | utils.task:decorator:275 - 添加页面：打不过跑路
2024-08-18 15:30:52.008 | DEBUG    | utils.task:decorator:275 - 添加页面：打不过怪
2024-08-18 15:30:52.009 | DEBUG    | utils.task:decorator:275 - 添加页面：红叉离开事件
2024-08-18 15:30:52.009 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_红色风险
2024-08-18 15:30:52.010 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_紫色风险
2024-08-18 15:30:52.011 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_白色未知
2024-08-18 15:30:52.011 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_蓝色打开
2024-08-18 15:30:52.011 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_金色收益
2024-08-18 15:30:52.013 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_蓝色收益
2024-08-18 15:30:52.013 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_绿色收益
2024-08-18 15:30:52.014 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_橙色插件
2024-08-18 15:30:52.014 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_白色退出
2024-08-18 15:30:52.014 | DEBUG    | utils.task:decorator:275 - 添加页面：选项_绿色治疗
2024-08-18 15:30:52.015 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_艾莲1
2024-08-18 15:30:52.016 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_艾莲2
2024-08-18 15:30:52.016 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_猫又1
2024-08-18 15:30:52.016 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_猫又2
2024-08-18 15:30:52.016 | DEBUG    | utils.task:decorator:275 - 添加页面：好感度_格莉丝1
2024-08-18 15:30:52.017 | DEBUG    | utils.task:decorator:275 - 添加页面：资源回收小组
2024-08-18 15:30:52.017 | DEBUG    | utils.task:decorator:275 - 添加页面：选择_鸣徽
2024-08-18 15:30:52.018 | DEBUG    | utils.task:decorator:308 - 添加条件操作：最大战斗次数
2024-08-18 15:30:52.027 | DEBUG    | utils.task:decorator:275 - 添加页面：战斗中
2024-08-18 15:30:52.749 | DEBUG    | utils.task:__call__:327 - 进入副本次数：0 当前页面：选择副本
2024-08-18 15:30:54.390 | DEBUG    | utils.task:__call__:327 - 进入副本次数：0 当前页面：选择副本等级
2024-08-18 15:30:56.546 | DEBUG    | utils.task:__call__:327 - 进入副本次数：0 当前页面：选择角色
2024-08-18 15:30:59.798 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:31:10.156 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:10.624 | DEBUG    | handle.others:grid_map:72 - 未找到路径
2024-08-18 15:31:12.336 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:12.784 | DEBUG    | handle.others:grid_map:72 - 未找到路径
2024-08-18 15:31:14.185 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：选择_鸣徽
2024-08-18 15:31:16.302 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：选择_鸣徽
2024-08-18 15:31:18.625 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:20.538 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:31:23.336 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:31:25.722 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:31:28.130 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:31:30.647 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:31:32.342 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:31:33.906 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：假面研究者
2024-08-18 15:31:35.811 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:31:38.123 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:31:40.427 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:40.807 | DEBUG    | handle.others:grid_map:66 - 未识别到地图信息
2024-08-18 15:31:42.530 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:42.909 | DEBUG    | handle.others:grid_map:66 - 未识别到地图信息
2024-08-18 15:31:44.646 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:47.080 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:48.857 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:51.124 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:52.936 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:55.141 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:31:56.599 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：呼叫增援_接应
2024-08-18 15:31:58.049 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：呼叫增援_入队
2024-08-18 15:31:59.301 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:32:01.150 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:02.962 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:32:04.771 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:06.986 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:09.221 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:10.815 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：异化检疫门
2024-08-18 15:32:12.935 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:32:15.276 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:32:17.558 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：通用点击事件
2024-08-18 15:32:19.770 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:21.065 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:32:22.779 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:24.548 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:24.922 | DEBUG    | handle.others:grid_map:66 - 未识别到地图信息
2024-08-18 15:32:26.594 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:28.780 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:29.164 | DEBUG    | handle.others:grid_map:66 - 未识别到地图信息
2024-08-18 15:32:30.838 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:33.170 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:34.435 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:32:35.720 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:32:36.990 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:32:38.224 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：确认操作
2024-08-18 15:32:39.753 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：目标位置
2024-08-18 15:32:41.586 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：地图层数
2024-08-18 15:32:55.937 | DEBUG    | utils.task:__call__:327 - 进入副本次数：1 当前页面：战斗中
2024-08-18 15:33:05.841 | ERROR    | utils.utils:screenshot:186 - 清理截图资源失败: DeleteDC failed
Exception in thread Thread-3 (detector_task):
Traceback (most recent call last):
  File "C:\Users\DAI\anaconda3\envs\py312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\DAI\anaconda3\envs\py312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\FUZHU\ZenlessZoneZero-Auto-master\fight\fight_zero.py", line 88, in detector_task
    img = screenshot()
          ^^^^^^^^^^^^
  File "D:\FUZHU\ZenlessZoneZero-Auto-master\utils\utils.py", line 146, in screenshot
    hwndDC = win32gui.GetWindowDC(Hwnd)  # 获取窗口设备上下文（DC）
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.error: (1400, 'GetWindowDC', '无效的窗口句柄。')

**Comment by IsSmallPigPig** [comment]
失去窗口焦点或最小化了就会清理失败

**Comment by DAI-HY** [comment]
> 失去窗口焦点或最小化了就会清理失败

但是一直是桌面置顶的，为什么会出现这种情况呢？

**Comment by sMythicalBird** [comment]
你应该是最小化之后启动的脚本，这时候捕获不到图像，删除了一个不存在的东西报错了，启动脚本的时候不要最小化游戏窗口

**Comment by DAI-HY** [comment]
ok 我再试试 感谢
