### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Dshez1** [sMythicalBird/ZenlessZoneZero-Auto#4]
2024-07-14 19:52:46.589 | DEBUG    | utils.init:<module>:31 - 初始化utils模块中
2024-07-14 19:52:46.610 | INFO     | utils.init:<module>:97 - 游戏窗口宽度为1280，高度为720,缩放因子为1.0,实际宽度为1280,实际高度为720
2024-07-14 19:52:46.611 | INFO     | utils.init:<module>:100 - 宽度缩放比例为1.0,高度缩放比例为1.0
2024-07-14 19:52:46.611 | INFO     | utils.init:<module>:101 - 菜单栏高度为22,左上角偏移量为(8.0,31.0)
2024-07-14 19:52:46.612 | DEBUG    | utils.download:check_file:58 - 开始检查文件！
Traceback (most recent call last):
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Program Files\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Program Files\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ZenlessZoneZero-Auto-master\main.py", line 3, in <module>
    from utils.task import task
  File "D:\ZenlessZoneZero-Auto-master\utils\__init__.py", line 8, in <module>
    from .download import check_file
  File "D:\ZenlessZoneZero-Auto-master\utils\download.py", line 94, in <module>
    check_file()
  File "D:\ZenlessZoneZero-Auto-master\utils\download.py", line 88, in check_file
    download_with_progressbar(DownLoadBaseUrl + file, file_path)
  File "D:\ZenlessZoneZero-Auto-master\utils\download.py", line 25, in download_with_progressbar
    response = requests.get(url, stream=True)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\ZenlessZoneZero-Auto-master\.venv\lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by lazydog28** [comment]
网络问题，重新请求试试，如果不行就再试试挂代理。
