### ISSUE TITLE
运行脚本报错

### ISSUE THREAD

**Issue by zhUpUp** [sMythicalBird/ZenlessZoneZero-Auto#7]
系统window11家庭版

Traceback (most recent call last):
  File "D:\ZenlessZoneZero-Auto-master\main.py", line 3, in <module>
    from utils.task import task
  File "D:\ZenlessZoneZero-Auto-master\utils\__init__.py", line 21, in <module>
    from .map import get_map_info, auto_find_way
  File "D:\ZenlessZoneZero-Auto-master\utils\map\__init__.py", line 8, in <module>
    from .components import get_map_info
  File "D:\ZenlessZoneZero-Auto-master\utils\map\components.py", line 13, in <module>
    from onnxruntime import InferenceSession
  File "D:\develop\python\3.12.4\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "D:\develop\python\3.12.4\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\develop\python\3.12.4\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: 动态链接库(DLL)初始化例程失败。

**Comment by zhangyushao0** [comment]
这个我也遇到了，我是重新安装onnxruntime库解决的
```

**Comment by zhUpUp** [comment]
> 这个我也遇到了，我是重新安装onnxruntime库解决的
> 
> ```python
> pip uninstall onnxruntime
> pip install onnxruntime
> ```

我重装过，还是报错

**Comment by lazydog28** [comment]
> > 这个我也遇到了，我是重新安装onnxruntime库解决的
> > ```python
> > pip uninstall onnxruntime
> > pip install onnxruntime
> > ```
> 
> 我重装过，还是报错

把 `site-packages` 文件夹里`onnxruntime`相关的文件全部删除干净再重新尝试安装。
```
pip install onnxruntime-gpu
```
如果还是不行的话，可以考虑python版本降低至`3.10`

**Comment by xzc9607** [comment]
我在新安装的win11上也出现了同样的错误，重装onnxruntime也没解决。想到是不是运行库缺失了，装了一下运行库合集解决了。
所以，可以尝试使用搜索引擎下载一个运行库合集，安装之后再次运行
